/*
Slurm Rest API

API to access and control Slurm.

API version: v0.0.38
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the Dbv0038ClusterAssociations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dbv0038ClusterAssociations{}

// Dbv0038ClusterAssociations Information about associations
type Dbv0038ClusterAssociations struct {
	Root *Dbv0038AssociationShortInfo `json:"root,omitempty"`
}

// NewDbv0038ClusterAssociations instantiates a new Dbv0038ClusterAssociations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0038ClusterAssociations() *Dbv0038ClusterAssociations {
	this := Dbv0038ClusterAssociations{}
	return &this
}

// NewDbv0038ClusterAssociationsWithDefaults instantiates a new Dbv0038ClusterAssociations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0038ClusterAssociationsWithDefaults() *Dbv0038ClusterAssociations {
	this := Dbv0038ClusterAssociations{}
	return &this
}

// GetRoot returns the Root field value if set, zero value otherwise.
func (o *Dbv0038ClusterAssociations) GetRoot() Dbv0038AssociationShortInfo {
	if o == nil || IsNil(o.Root) {
		var ret Dbv0038AssociationShortInfo
		return ret
	}
	return *o.Root
}

// GetRootOk returns a tuple with the Root field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0038ClusterAssociations) GetRootOk() (*Dbv0038AssociationShortInfo, bool) {
	if o == nil || IsNil(o.Root) {
		return nil, false
	}
	return o.Root, true
}

// HasRoot returns a boolean if a field has been set.
func (o *Dbv0038ClusterAssociations) HasRoot() bool {
	if o != nil && !IsNil(o.Root) {
		return true
	}

	return false
}

// SetRoot gets a reference to the given Dbv0038AssociationShortInfo and assigns it to the Root field.
func (o *Dbv0038ClusterAssociations) SetRoot(v Dbv0038AssociationShortInfo) {
	o.Root = &v
}

func (o Dbv0038ClusterAssociations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dbv0038ClusterAssociations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Root) {
		toSerialize["root"] = o.Root
	}
	return toSerialize, nil
}

type NullableDbv0038ClusterAssociations struct {
	value *Dbv0038ClusterAssociations
	isSet bool
}

func (v NullableDbv0038ClusterAssociations) Get() *Dbv0038ClusterAssociations {
	return v.value
}

func (v *NullableDbv0038ClusterAssociations) Set(val *Dbv0038ClusterAssociations) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0038ClusterAssociations) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0038ClusterAssociations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0038ClusterAssociations(val *Dbv0038ClusterAssociations) *NullableDbv0038ClusterAssociations {
	return &NullableDbv0038ClusterAssociations{value: val, isSet: true}
}

func (v NullableDbv0038ClusterAssociations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0038ClusterAssociations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
