/*
Slurm Rest API

API to access and control Slurm.

API version: v0.0.38
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the Dbv0038JobStepTask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dbv0038JobStepTask{}

// Dbv0038JobStepTask task details
type Dbv0038JobStepTask struct {
	// distribution
	Distribution *string `json:"distribution,omitempty"`
}

// NewDbv0038JobStepTask instantiates a new Dbv0038JobStepTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0038JobStepTask() *Dbv0038JobStepTask {
	this := Dbv0038JobStepTask{}
	return &this
}

// NewDbv0038JobStepTaskWithDefaults instantiates a new Dbv0038JobStepTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0038JobStepTaskWithDefaults() *Dbv0038JobStepTask {
	this := Dbv0038JobStepTask{}
	return &this
}

// GetDistribution returns the Distribution field value if set, zero value otherwise.
func (o *Dbv0038JobStepTask) GetDistribution() string {
	if o == nil || IsNil(o.Distribution) {
		var ret string
		return ret
	}
	return *o.Distribution
}

// GetDistributionOk returns a tuple with the Distribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0038JobStepTask) GetDistributionOk() (*string, bool) {
	if o == nil || IsNil(o.Distribution) {
		return nil, false
	}
	return o.Distribution, true
}

// HasDistribution returns a boolean if a field has been set.
func (o *Dbv0038JobStepTask) HasDistribution() bool {
	if o != nil && !IsNil(o.Distribution) {
		return true
	}

	return false
}

// SetDistribution gets a reference to the given string and assigns it to the Distribution field.
func (o *Dbv0038JobStepTask) SetDistribution(v string) {
	o.Distribution = &v
}

func (o Dbv0038JobStepTask) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dbv0038JobStepTask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Distribution) {
		toSerialize["distribution"] = o.Distribution
	}
	return toSerialize, nil
}

type NullableDbv0038JobStepTask struct {
	value *Dbv0038JobStepTask
	isSet bool
}

func (v NullableDbv0038JobStepTask) Get() *Dbv0038JobStepTask {
	return v.value
}

func (v *NullableDbv0038JobStepTask) Set(val *Dbv0038JobStepTask) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0038JobStepTask) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0038JobStepTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0038JobStepTask(val *Dbv0038JobStepTask) *NullableDbv0038JobStepTask {
	return &NullableDbv0038JobStepTask{value: val, isSet: true}
}

func (v NullableDbv0038JobStepTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0038JobStepTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
