/*
Slurm Rest API

API to access and control Slurm.

API version: v0.0.38
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the Dbv0038ClusterController type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dbv0038ClusterController{}

// Dbv0038ClusterController Information about controller
type Dbv0038ClusterController struct {
	// Hostname
	Host *string `json:"host,omitempty"`
	// Port number
	Port *int32 `json:"port,omitempty"`
}

// NewDbv0038ClusterController instantiates a new Dbv0038ClusterController object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0038ClusterController() *Dbv0038ClusterController {
	this := Dbv0038ClusterController{}
	return &this
}

// NewDbv0038ClusterControllerWithDefaults instantiates a new Dbv0038ClusterController object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0038ClusterControllerWithDefaults() *Dbv0038ClusterController {
	this := Dbv0038ClusterController{}
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *Dbv0038ClusterController) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0038ClusterController) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *Dbv0038ClusterController) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *Dbv0038ClusterController) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *Dbv0038ClusterController) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0038ClusterController) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *Dbv0038ClusterController) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *Dbv0038ClusterController) SetPort(v int32) {
	o.Port = &v
}

func (o Dbv0038ClusterController) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dbv0038ClusterController) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	return toSerialize, nil
}

type NullableDbv0038ClusterController struct {
	value *Dbv0038ClusterController
	isSet bool
}

func (v NullableDbv0038ClusterController) Get() *Dbv0038ClusterController {
	return v.value
}

func (v *NullableDbv0038ClusterController) Set(val *Dbv0038ClusterController) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0038ClusterController) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0038ClusterController) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0038ClusterController(val *Dbv0038ClusterController) *NullableDbv0038ClusterController {
	return &NullableDbv0038ClusterController{value: val, isSet: true}
}

func (v NullableDbv0038ClusterController) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0038ClusterController) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
