/*
Slurm Rest API

API to access and control Slurm.

API version: v0.0.38
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrestapi

import (
	"encoding/json"
)

// checks if the Dbv0038ClusterInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dbv0038ClusterInfo{}

// Dbv0038ClusterInfo struct for Dbv0038ClusterInfo
type Dbv0038ClusterInfo struct {
	Meta *Dbv0038Meta `json:"meta,omitempty"`
	// Slurm errors
	Errors []Dbv0038Error `json:"errors,omitempty"`
	// Array of jobs
	Clusters []Dbv0038Cluster `json:"clusters,omitempty"`
}

// NewDbv0038ClusterInfo instantiates a new Dbv0038ClusterInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0038ClusterInfo() *Dbv0038ClusterInfo {
	this := Dbv0038ClusterInfo{}
	return &this
}

// NewDbv0038ClusterInfoWithDefaults instantiates a new Dbv0038ClusterInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0038ClusterInfoWithDefaults() *Dbv0038ClusterInfo {
	this := Dbv0038ClusterInfo{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *Dbv0038ClusterInfo) GetMeta() Dbv0038Meta {
	if o == nil || IsNil(o.Meta) {
		var ret Dbv0038Meta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0038ClusterInfo) GetMetaOk() (*Dbv0038Meta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *Dbv0038ClusterInfo) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given Dbv0038Meta and assigns it to the Meta field.
func (o *Dbv0038ClusterInfo) SetMeta(v Dbv0038Meta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Dbv0038ClusterInfo) GetErrors() []Dbv0038Error {
	if o == nil || IsNil(o.Errors) {
		var ret []Dbv0038Error
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0038ClusterInfo) GetErrorsOk() ([]Dbv0038Error, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Dbv0038ClusterInfo) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Dbv0038Error and assigns it to the Errors field.
func (o *Dbv0038ClusterInfo) SetErrors(v []Dbv0038Error) {
	o.Errors = v
}

// GetClusters returns the Clusters field value if set, zero value otherwise.
func (o *Dbv0038ClusterInfo) GetClusters() []Dbv0038Cluster {
	if o == nil || IsNil(o.Clusters) {
		var ret []Dbv0038Cluster
		return ret
	}
	return o.Clusters
}

// GetClustersOk returns a tuple with the Clusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0038ClusterInfo) GetClustersOk() ([]Dbv0038Cluster, bool) {
	if o == nil || IsNil(o.Clusters) {
		return nil, false
	}
	return o.Clusters, true
}

// HasClusters returns a boolean if a field has been set.
func (o *Dbv0038ClusterInfo) HasClusters() bool {
	if o != nil && !IsNil(o.Clusters) {
		return true
	}

	return false
}

// SetClusters gets a reference to the given []Dbv0038Cluster and assigns it to the Clusters field.
func (o *Dbv0038ClusterInfo) SetClusters(v []Dbv0038Cluster) {
	o.Clusters = v
}

func (o Dbv0038ClusterInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dbv0038ClusterInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Clusters) {
		toSerialize["clusters"] = o.Clusters
	}
	return toSerialize, nil
}

type NullableDbv0038ClusterInfo struct {
	value *Dbv0038ClusterInfo
	isSet bool
}

func (v NullableDbv0038ClusterInfo) Get() *Dbv0038ClusterInfo {
	return v.value
}

func (v *NullableDbv0038ClusterInfo) Set(val *Dbv0038ClusterInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0038ClusterInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0038ClusterInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0038ClusterInfo(val *Dbv0038ClusterInfo) *NullableDbv0038ClusterInfo {
	return &NullableDbv0038ClusterInfo{value: val, isSet: true}
}

func (v NullableDbv0038ClusterInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0038ClusterInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
